initramfs: Improve init script

diff --git a/installer/gentoo/initramfs/init b/installer/gentoo/initramfs/init
--- a/installer/gentoo/initramfs/init
+++ b/installer/gentoo/initramfs/init
@@ -29,6 +29,17 @@ sread() {
 
 trap rescue_shell EXIT
 
+info ' _     _____ _ _  ___               ___       _     _ _ '
+info '| |__ |___ /| | |/ _ \   __      __/ _ \ _ __| | __| | |'
+info '| '_ \  |_ \| | | | | |  \ \ /\ / / | | | '__| |/ _` | |'
+info '| | | |___) | | | |_| |   \ V  V /| |_| | |  | | (_| |_|'
+info '|_| |_|____/|_|_|\___( )   \_/\_/  \___/|_|  |_|\__,_(_)'
+info '                     |/                                 '
+
+info "The initramfs init script successfully loaded!"
+info "Start to initialize the system..."
+
+info "Mount the pseudo filesystesms..."
 mount -t devtmpfs udev /dev
 mount -t proc proc /proc
 mount -t sysfs sysfs /sys
@@ -37,11 +48,13 @@ mount -t tmpfs tmpfs /tmp
 # We use udev here. Make sure not to use any uevnet helper.
 [ -w /sys/kernel/uevent_helper ] && echo > /sys/kernel/uevent_helper
 
+info "Start the udev daemon..."
 /lib/systemd/systemd-udevd --daemon --resolve-names="never"
 udevadm trigger --type="subsystems" --action="add"
 udevadm trigger --type="devices" --action="add"
 udevadm settle || :
 
+info "Parse kernel parameters..."
 read -r cmdline < /proc/cmdline
 for cmd in $cmdline
 do
@@ -53,10 +66,20 @@ do
                     count=0
                     while true
                     do
-                        # shellcheck disable=SC2015
-                        root=$(findfs PARTUUID="${cmd#PARTUUID=}") && break || :
+                        if root=$(findfs PARTUUID="${cmd#PARTUUID=}")
+                        then
+                            info "Detected the root partition."
+                            info "root=$root"
+                            break
+                        fi
+
                         count=$((count+1))
-                        [ "$count" = 50 ] && exit 1
+                        if [ "$count" = 50 ]
+                        then
+                            error "Failed to detect the root partition!"
+                            exit 1
+                        fi
+
                         sleep 0.3
                     done
                     ;;
@@ -65,34 +88,77 @@ do
     esac
 done
 
-sread "Enter a passphrase for the root partition: " passphrase
-luks_passphrase=$(mkpassphrase "${passphrase?}" | sed -n "s/result = \(.*\)/\1/p")
+info "Decrypt the root partition..."
+while true
+do
+    sread "Enter a passphrase for the root partition: " passphrase
+    luks_passphrase=$(mkpassphrase "${passphrase?}" \
+        | sed -n "s/result = \(.*\)/\1/p")
 
-if ! echo "$luks_passphrase" | xxd -revert -plain \
-    | cryptsetup luksOpen --key-file="-" "/dev/$root" root
-then
-    error "Failed to open the root partition!"
-    error "The system you're on might be modified to steal your information!"
-    printf "Do you want to open the root partition using a recovery passphrase? [y/n]: "
-    read -r answer
-    if [ "$answer" = "y" ] || [ "$answer" = "Y" ]
+    if ! echo "$luks_passphrase" | xxd -revert -plain | cryptsetup luksOpen \
+        --key-file="-" "/dev/$root" root
     then
-        sread "Enter a recovery passphrase for the root partition: " recovery_passphrase
-        echo "${recovery_passphrase?}" \
-            | cryptsetup luksOpen --key-file="-" "/dev/$root" root
-    else
-        exit 1
+        error "Failed to open the root partition!"
+        error "The system you're on might be modified to steal your information!"
+        while true
+        do
+            printf "Do you want to open the root partition using a recovery passphrase? [y/n]: "
+            read -r answer
+            case "$answer" in
+                y* | Y*)
+                    while true
+                    do
+                        sread "Enter a recovery passphrase for the root partition: " \
+                            recovery_passphrase
+                        if ! echo "${recovery_passphrase?}" | cryptsetup luksOpen \
+                            --key-file="-" "/dev/$root" root
+                        then
+                            error "Failed to open the root partition! Try again."
+                        else
+                            break
+                        fi
+                    done
+                    break
+                    ;;
+                n* | N*)
+                    while true
+                    do
+                        printf "Do you want to execute a shell for debugging? [y/n]: "
+                        read -r shanswer
+                        case "$shanswer" in
+                            y* | Y*)
+                                exit 1
+                                ;;
+                            n* | N*)
+                                break
+                                ;;
+                            *)
+                                error "Invalid input! Try again."
+                                ;;
+                        esac
+                    done
+                    break
+                    ;;
+                *)
+                    error "Invalid input! Try again."
+                    ;;
+            esac
+        done
     fi
-fi
+done
 
+info "Mount the root partition!"
 mount /dev/mapper/root /mnt/root
-mount -t btrfs -o "noatime,rw,space_cache=v2,subvolid=5,subvol=/deploy/target" \
+mount -t btrfs -o noatime,rw,space_cache=v2,subvolid=5,subvol=/deploy/target \
     /dev/mapper/root /mnt/root/deploy/target
 
+info "Stop the udev daemon..."
 udevadm control --exit
 
+info "Clean up..."
 umount -R /dev
 umount /proc
 umount /sys
 
+info "Execute the init process!"
 exec switch_root /mnt/root/deploy/target /sbin/init
